tasks/main.yml

support for the map filter with default was added in jinja2 2.11.0
https://jinja.palletsprojects.com/en/2.11.x/changelog/#version-2-11-0
But some of our supported platforms use jinja2 2.10, so we need to
rewrite the code to not use map/default.
Jinja2 gives warnings/errors like this:
```
TASK [linux-system-roles.certificate : Ensure provider packages are installed] ***
task path: tasks/main.yml:26
[WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
Unexpected keyword argument 'default'
...
TASK [linux-system-roles.certificate : Ensure certificate requests] ************
task path: tasks/main.yml:104
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The …
```

do not use jinja2 map filter with default param

---

module_utils/certificate/providers/__init__.py
module_utils/certificate/providers/certmonger.py
tests/tasks/assert_certificate_parameters.yml

The bug was caused by relative imports inside module_utils. Certificate role have multiple files inside the "module_utils" directory and they are referenced by .something instead of ansible.module_utils.certificate.something. Using the full reference gets the problem fixed for ansible >=2.8.
* Closes #46

Using full imports instead of relative for module_utils

---

module_utils/certificate/providers/base.py

Six lib included in ansible didn't have ensure_text function before ansible 2.9.
* Closes #48

Using to_text instead of ensure_text

---

module_utils/certificate/providers/base.py

For earlier versions of Python the dict order was not maintained and
comparing key_usage of a certificate and a new request resulted in a
new certificate request, even if the keys were not changed, only
reordered.
According to section 4.2.1.3 of RFC 5280 [1], the key_usage is a bit string
so, independent of the order the user requested, they will have the
same order in the certificate and certificate sign request.
Ordering the keys before comparing the request and the certificate
ensures idempotency, independent of python's version.
Fixes #45
[1] https://tools.ietf.org/html/rfc5280#page-30

Fix idempotence issue with python version < 3.5

---

tests/tasks/setup_ipa.yml

Change version of ansible-freeipa to 0.2.0 to fix IPA_MODULES import
issue
https://github.com/linux-system-roles/certificate/issues/60

Update version of ansible-freeipa

---

module_utils/certificate_lsr/providers/__init__.py
module_utils/certificate_lsr/providers/certmonger.py

Testing the suggestion from @sivel:
Applying this network example to certificate:
replacing
from ansible.module_utils.network_lsr.nm.provider import NetworkManagerProvider,
with
from ansible.module_utils.network_lsr.nm import provider
and then use provider.NetworkManagerProvider

Collections - workaround for the module_utils path finding issue in ansible 2.9

---

tests/tasks/assert_certificate_parameters.yml

Tests was failing with dependency issue while
installing certreader as pip was installed with older version.
Thus added fix to use latest pip.
Signed-off-by: Anuja More <amore@redhat.com>

Use latest pip.

---

library/certificate_request.py

Adding "WARNING: Do not use this module directly! It is only for role internal use." to certificate_request DOCUMENTATION.

RHELPLAN-69928  Add a note to each module Doc to indicate it is private

---

meta/main.yml
tests/tasks/setup_ipa.yml

From now the `rhel-8-y` status is the latest unreleased RHEL-8 and the `rhel-x` status is pre-released RHEL-9.

CI: Add support for RHEL-9

---

tests/tasks/setup_ipa.yml

Note: having the module 'archive' makes the role fail with an error
"couldn't resolve module/action 'archive'." if executed with ansible-
navigator.
Ref: bz1984182

Instead of the archive module, use "tar" command for backup.

---

tests/tasks/setup_ipa.yml

Also, fixing a warning issue: Do not warn about unarchive.
Ref: bz1984182, bz1987096

Instead of the unarchive module, use "tar" command for backup.

---

library/certificate_request.py
module_utils/certificate_lsr/providers/base.py
tasks/main.yml

In the condition of param_sha1 == file_sha1, the condition "param !=
cur_script (contents of file)" never be true and never be executed.
It was introduced in commit e5fe0392f5491293719eddbf5afb29611748c55c
System Roles should consistently use ansible_managed in configuration files it manages
Replace ansible_managed_new with __header
@richm, @rjeffman, so sorry... I revisited the commit e5fe0392f5491293719eddbf5afb29611748c55c and realized it introduced the code which never been executed. This patch removes it. It does not do a bad thing, but we should not include the garbage... :(
And if ok, I'd like to replace the parameter `ansible_managed_new` with `__header` to adjust to the other roles. Thanks.

Remove the unnecessary code

---

tests/tests_basic_ipa.yml
tests/tests_basic_self_signed.yml
tests/tests_dns_ip_email.yml
tests/tests_fs_attrs.yml
tests/tests_key_size.yml
tests/tests_key_usage_and_extended_key_usage.yml
tests/tests_many_self_signed.yml
tests/tests_no_auto_renew.yml
tests/tests_not_wait_for_cert.yml
tests/tests_principal.yml
tests/tests_provider.yml
tests/tests_run_hooks.yml
tests/tests_subject.yml
tests/tests_subject_complex.yml
tests/tests_wrong_provider.yml

This is part of the effort to allow CI tests run in the serialized
manner on one VM for shortening the duration of the CI tests. In
the current tests, the same certificate file path is shared and
there is no cleaning up implemented. When multiple tests run
sequentially, some attribute, e.g., the file ownership, could be
inherited from the previous tests, which could make the test fail
in the attribute verification. To avoid the false negative failure,
this commit chooses different certificate file name per test.

Let each test use a different certificate file name

---

.github/workflows/changelog_to_tag.yml

Sorry, there was a bug in the pr "Add changelog_to_tag.yml to .github/workflows (#125)".

[citest skip] Fix a bash bug in changelog_to_tag.yml, which unexpectedly expanded "*".

---

CHANGELOG.md

[1.1.6] - 2022-07-19
--------------------
- none
- none
- make all tests work with gather_facts: false (#121)
Ensure tests work when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#122)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#123)
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

Version 1.1.6 - CHANGELOG.md [citest skip]

---

vars/Debian.yml

The python 2 packages don't exist any more in current stable Debian 11
and Ubuntu 22.04 LTS. Use the python3-* packages (vars/main.yml has the
correct ones).
---
Spotted in https://github.com/linux-system-roles/cockpit/pull/68 , this role does not work at all any more in current Debian/Ubuntu.

Move Debian to Python 3 packages

---

CHANGELOG.md

[1.1.7] - 2022-09-19
--------------------
- none
- Move Debian to Python 3 packages
The python 2 packages don't exist any more in current stable Debian 11
and Ubuntu 22.04 LTS. Use the python3-* packages (vars/main.yml has the
correct ones).
- changelog_to_tag action - support other than "master" for the main branch name (#129)
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

Version 1.1.7 - CHANGELOG.md [citest skip]

---

.github/workflows/woke.yml
CHANGELOG.md
tests/tasks/setup_ipa.yml

Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Note: this commit uses the customized woke placed locally in
.github/actions/custom-woke-action. It will be replaced with
the official woke once get-woke/woke#252
(Add an option "--count-only-error-for-failure") is processed.
CHANGELOG.md - cleanup non-inclusive words.
tests/tasks/setup_ipa.yml - Apply "wokeignore:rule"

Add check for non-inclusive language

---

tests/tests_run_hooks.yml

In the tests_run_hooks.yml test script, allow the timestamp of run_before and run_after to be equal to the certificate timestamp.

Fix assert in tests_run_hooks.yml

---

.ansible-lint
.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-plugin-scan.yml
.github/workflows/ansible-test.yml
.github/workflows/codeql.yml
.github/workflows/python-unit-test.yml

Update tox-lsr to 2.13.2
Update ansible-lint configuration
Add support for merge queues to github actions
This doesn't mean all system roles support merge queues,
this is just a preliminary step
See https://github.com/linux-system-roles/.github/pull/21
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

update tox-lsr to 2.13.2; update ansible-lint configuration; start of support for merge queues

---

templates/get_ansible_managed.j2

Add role name to the generated script files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.

Fingerprint RHEL System Role managed config files

---

tests/tasks/check_header.yml
tests/templates/get_ansible_managed.j2
tests/tests_run_hooks.yml

Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes two parameters:
* `__file` - required - the full path of the file to check e.g. `/etc/realmd.conf`
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-files
for the different types of comment styles supported.
Example:
```
- name: Check generated files for …
```

test: check generated files for ansible_managed, fingerprint

---

pylintrc

Remove `no-space-check` and `overgeneral-exception`
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

ci: fix pylintrc issues

---

tasks/main.yml

This allows the certificate role to easily generate certs, keys
for use in tests of other system roles.  This eliminates the
anti-patterns like
https://github.com/linux-system-roles/logging/blob/main/tests/tests_server.yml#L16
where the test has to hard-code all of the paths that should be
only internal to the certificate role, and
https://github.com/linux-system-roles/logging/blob/main/tests/tests_server.yml#L212
where the role has to explicitly stop tracking the cert.
The caller of the role uses `certificate_test_mode: true` to activate this
feature.  I deliberately did not document this in the README because I don't
want end users to use this, only dev/qe.
The certs are returned in `certificate_test_certs`.  This is a `dict`.  Each
key is the cert name as passed in …

test: easily generate certs for tests for other roles

---

README.md
library/certificate_request.py
module_utils/certificate_lsr/providers/base.py
tasks/main.yml
tests/tests_fs_attrs.yml

Enhancement: Allow seting of certificate and key files mode attribute through the use of the 'mode' parameter, when using the certmonger provider.
Reason: Previously, the certificate files generated by the certmonger provider used a default file mode that may not be suitable for some tools or for some more restricted environments.
Result: The file mode attribute can now be set using the same roles as Ansible's file mode parameter, accepting either a string or an integer.
Issue Tracker Tickets (Jira or BZ if any): https://bugzilla.redhat.com/show_bug.cgi?id=2180902

feat: Allow setting certificate and key files mode

---

.github/workflows/python-unit-test.yml

As of June 19th, 2023, Python 2.7 is not available on Github's software cache for Ubuntu 20.04 workflow runners. To keep running unit tests using Python 2.7, the package is installed through Ubunut's repositories using `apt install`.

ci: Use Ubuntu repository for Python 2.7

---

.pre-commit-config.yaml

Update pre-commit hooks to newer versions as some were failing due to being too old.

test: Update pre-commit hooks

---

tests/library/certtojson.py
tests/tasks/assert_certificate_parameters.yml
tests/tasks/setup_ipa.yml

certreader, which provides certreader2json is not activelly maintained and is not compiling in all platforms supported by the certificate linux system role.
This patch removes its dependency by providing a similar certificate parser.

ci: Remove certreader dependency

---

tests/tasks/setup_ipa.yml

As certificate system role uses an IPA server to test certmonger provider, the ipaserver node has to have a FQDN for IPA to be installed. For the RedHat family of distros, from CentOS/RHEL 7+ and newer, automatic detection of Ansible's hostname may not select 'systemd' strategy, failing to set the hostnade FQDN. This failure often happens when running the tests locally with 'qemu'.
This patch ensure that the 'systemd' strategy is used to set hostname.

tests: Ensure ipaserver hostname is a FQDN

---

tests/library/certtojson.py
tests/tasks/assert_certificate_parameters.yml

This patch drop usage of pip to download and install test dependencies, and in its place use Ansible's builtin `package` module. The advantage is to use the distribution official packages, which are easier to trace the source.

ci: Remove package installation through pip

---

library/certificate_request.py
module_utils/certificate_lsr/providers/base.py
module_utils/certificate_lsr/providers/certmonger.py
tests/tests_key_size.yml
tests/tests_key_size_reissue.yml

**Resolves:** 
When requesting a certificate key size is not evaluated to consider a new certificate has to be requested.
**Result:**
This patch adds 'key_size' to the metadata comparison to determine if a new certificate request must be performed.
**Issue Tracker Tickets (Jira or BZ if any):** [RHBZ#2186057](https://bugzilla.redhat.com/show_bug.cgi?id=2186057)

fix: Re-issue certificate if key size changes

---

.ansible-lint
.ostree/get_ostree_data.sh
meta/collection-requirements.yml
tasks/main.yml
tasks/set_vars.yml
tests/tasks/assert_certificate_parameters.yml
tests/tasks/setup_ipa.yml

The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …

refactor: improve support for ostree systems

---

.ostree/packages-runtime-SUSE-ALP.txt
.ostree/packages-testing-SUSE-ALP.txt
vars/ALP-Dolomite.yml

Enhancement: Add support for SUSE ALP-Dolomite in the certificate Ansible role.
Reason: This enhancement aims to introduce compatibility by adjusting file paths, package dependencies
Result: Updated the certificate role for SUSE ALP-Dolomite
Issue Tracker Tickets (Jira or BZ if any):na

ci: Add support for SUSE ALP-Dolomite

---

.github/CODEOWNERS

Otherwise, I cannot merge PRs from CLI with approval

chore: Add spetrosi as a code owner

---

module_utils/certificate_lsr/providers/certmonger.py

When trying to resubmit a certificate request that had the key file removed, "getcert" hangs indefinitely, causing the role to not respond.
This workaround checks if the private key file has been removed and fails ressubmiting the certificate request until the situation is fixed, by the user, using 'getcert stop-tracking --id <cert ID>'.
Issue Tracker Tickets (Jira or BZ if any): RHEL-13333

fix: Workaround getcert issue when cert key-file is missing
